# fly.toml app configuration file generated for dnd-dungeon-master-companion on 2023-11-29T13:17:43-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dnd-dungeon-master-companion"
primary_region = "ord"

[build]

[env]
  PORT = 8080

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
